<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <AssemblyName>truascension</AssemblyName>
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
  </PropertyGroup>

  <ItemGroup>
    <Reference Include="sts2">
      <HintPath>C:\Program Files (x86)\Steam\steamapps\common\Slay the Spire 2\data_sts2_windows_x86_64\sts2.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="GodotSharp">
      <HintPath>C:\Program Files (x86)\Steam\steamapps\common\Slay the Spire 2\data_sts2_windows_x86_64\GodotSharp.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="0Harmony">
      <HintPath>C:\Program Files (x86)\Steam\steamapps\common\Slay the Spire 2\data_sts2_windows_x86_64\0Harmony.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="codex.sts2.endlessmode">
      <HintPath>C:\Users\taman\OneDrive\Documents\Programmation\slay the spire 2 - mods\v1.9 for MAIN V0.103.2 and PUBLIC BETA v0.104-537-1-9-1777478978\codex.sts2.endlessmode.dll</HintPath>
      <Private>false</Private>
    </Reference>
  </ItemGroup>

</Project>
